"""Initial migration.

Revision ID: 4c39ea0312e8
Revises: 
Create Date: 2023-04-19 12:40:29.261336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c39ea0312e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['CampID'])

    with op.batch_alter_table('refugee', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['RefugeeID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refugee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
