"""Migration 2.

Revision ID: a76885f27a22
Revises: 4c39ea0312e8
Create Date: 2023-04-19 15:08:17.305537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a76885f27a22'
down_revision = '4c39ea0312e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CampEmail', sa.String(length=90), nullable=False))
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=False))
        batch_op.alter_column('CampName',
               existing_type=mysql.VARCHAR(length=90),
               nullable=False)
        batch_op.alter_column('CampAddress',
               existing_type=mysql.VARCHAR(length=90),
               nullable=False)
        batch_op.drop_column('AdminName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AdminName', mysql.VARCHAR(length=90), nullable=True))
        batch_op.alter_column('CampAddress',
               existing_type=mysql.VARCHAR(length=90),
               nullable=True)
        batch_op.alter_column('CampName',
               existing_type=mysql.VARCHAR(length=90),
               nullable=True)
        batch_op.drop_column('password')
        batch_op.drop_column('CampEmail')

    # ### end Alembic commands ###
